version: "3"

services:

  dev:
    build:
      dockerfile: docker/Dockerfile
      context: .
    ports:
    - 8080:8080

  get_token:
    build:
      dockerfile: docker/docker_token/Dockerfile
      context: .
